const messageRouter = require("./messageRoute");
const userRouter = require("./userRoute");
const groupRouter = require("./groupRoute");
const loginRouter = require("./loginRoute");
const router = require("express").Router();
const { authMiddleware } = require("../middleware/authMiddleware");
router.use("/auth/message", messageRouter);
router.use("/auth/user", userRouter);
router.use("/auth/group", groupRouter);
router.use("/auth", loginRouter);
module.exports = router;
